### ISSUE TITLE
Out of memory during second boot

### ISSUE THREAD

**Issue by mapagm** [doitdiy-ai/pi-boot-and-encrypt#1]
Hello,

I'm trying to use the script on Raspberry Pi 3 b+ (Raspberry Pi OS with desktop, Kernel version: 5.10) and during second boot I get the error:
`[33.445273] Out of memory: Killed process 105 (sdmem) total-vm:1220708kB, anon-rss:863528kB, file-rss:1172kB, shmem-rss:0kB, UID:0 pgtables:1202kB oom_score_adj:0
Killed`

Could You give me any hint please?

**Comment by doitdiy-ai** [comment]
How much RAM does the raspberry pi have? 
And which version of raspberry pi os are you using? Buster or Bullseye?

**Comment by mapagm** [comment]
Raspberry Pi 3 b+ have 1 GB of RAM and I'm using latest Raspberry Pi OS Bullseye.

**Comment by doitdiy-ai** [comment]
Ah ok, Bullseye won't work yet, I've seen issues with initramfs. 
Also, I'm pretty sure 1 Gb won't work. The initial encryption uses RAM as temporary disk space and it'll need more than 1 gb.

I have tried it however using a USB memory stick, and that worked as well. 

Procedure is exactly the same,  just make sure the usb stick is in the raspberry pi before you give the encrypt command.

**Comment by mapagm** [comment]
Ok, so the plan is:
1. Flash SD card with Raspbian Buster
2. Use Your script
3. Plug the SD card to RPi
4. Plug an USB stick to RPi
5. BOOT
6. Rest of the procedure like in the description.

Is that correct?

**Comment by doitdiy-ai** [comment]
Should be yes. Note, the usb stick will be wiped, so don't have any data on there that needs to be kept.

**Comment by mapagm** [comment]
Ok, so.... I realized the plan above and it seems everything work well! THANK YOU very much!

**Comment by doitdiy-ai** [comment]
Great, thanks for trying it out!

**Comment by doitdiy-ai** [comment]
Just a quick update: with the latest raspberry pi OS (1/28/2022), made some updates to the script, and Bullseye is now supported as well.
