### ISSUE TITLE
Powershell syntax errors

### ISSUE THREAD

**Issue by Loggsie** [doitdiy-ai/pi-boot-and-encrypt#2]
Hi,

Can you please assist. Editing execution policies via Group Policy and attempting to run the script generates amperstand syntax errors. I am running Windows 11 Pro with PS version 5.1.22621.608.

Thanks

**Comment by doitdiy-ai** [comment]
Hi there,

I just tried it with PS version 5.1.22621.963, and I'm not seeing any syntax errors. (And execution policy set as: `Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser`)

Would you mind opening boot-config.ps1 in notepad, and posting the first few lines here? I'm guessing the github HTML made it into the ps1 file as well...

Thanks.

**Comment by Loggsie** [comment]
Fathomed the issue and the HTML had made it into the script. Copied and pasted the script text from the browser into notepad rather than downloading the powershell file and saved it with a .ps1 extension. The script GUI loads as expected now after disabling powershell execution protections. 

Issue closed 👍
